---
title: "Flexdashboard - NY NOAA Dataset (simple random sample of 3000 observations from 2000-2010)"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse) #loads tidyverse package
library(p8105.datasets) #loads p8105.datasets package
library(plotly) #loads plotly package
library(flexdashboard) #loads flexdashboard package
```

```{r load_dataset, include=FALSE}
data("ny_noaa", package = "p8105.datasets") #loads ny_noaa dataset

ny_noaa = 
  ny_noaa %>% 
  filter(date > "1999-12-31") %>%  #keeps only data after Dec 31, 1999 
  sample_n(3000) #takes random sample of 3000 observations

ny_noaa = 
  ny_noaa %>% 
    janitor::clean_names() %>% #cleans variable names
  separate(date, into = c("year", "month", "day"), sep = '-') %>% #separates date variable into year, month, day variables
  mutate(id = as.factor(id), month = as.numeric(month), year = as.numeric(year), day = as.numeric(day), prcp = as.numeric(prcp), snow = as.numeric(snow), snwd = as.numeric(snow), tmax = as.numeric(tmax), tmin = as.numeric(tmin)) %>% #converts variables to proper classes
  mutate(month = month.abb[month]) %>% #replaces month number with name
  mutate(month = factor(month, levels = month.abb)) %>% #converts month name to factor variable
  arrange(id, year, month, day) %>% #arranges data by id, year, month, and day
  mutate(prcp_mm = prcp / 10, tmax_c = tmax / 10, tmin_c = tmin / 10) #convers prcp from tenths of mm to mm and converts temperatures from tenths of degrees c to degrees c
```


Column {data-width=500}
-----------------------------------------------------------------------

### Snowfall by Minimum Temperature, 2000-2010

```{r scatter_plot}
ny_noaa %>%
  mutate(text_label = str_c("Month: ", month, "Day: ", day, "\nYear: ", year, "\nStation ID: ", id)) %>% #creates label for hovering over text
  plot_ly(
    x = ~tmin_c, y = ~snow, type = "scatter", mode = "markers",
    color = ~month, text = ~text_label, alpha = 0.5) %>% #creates scatterplot
  layout(xaxis = list(title = 'Minimum Temperature (C)'), yaxis = list(title = 'Snowfall (mm)'), legend = list(title = list(text = 'Month'))) #adds labels
```

Column {data-width=500}
-----------------------------------------------------------------------

### Maximum Temperature by Year, 2000-2010

```{r box_plot}
ny_noaa %>% 
  mutate(year = as.factor(year)) %>% #creates label for hovering over text
  plot_ly(y = ~tmax_c, color = ~year, type = "box", colors = "viridis") %>% #creates boxplot
  layout(xaxis = list(title = 'Year'), yaxis = list(title = 'Maximum Temperature (C)'), legend = list(title = list(text = 'Year'))) #adds labels
```

### Average Preciptation by Month, 2000-2010

```{r bar_chart}
ny_noaa %>% 
  group_by(month) %>% #groups data by month
  summarize(prcp_avg = mean(prcp_mm, na.rm = TRUE)) %>% #calculates mean precipitation value for each month, excluding NA values
  plot_ly(x = ~month, y = ~prcp_avg, color = ~month, type = "bar", colors = "viridis") %>% #creates barchart
  layout(xaxis = list(title = 'Month'), yaxis = list(title = 'Average Precipitation (mm)'), legend = list(title = list(text = 'Month'))) #adds labels
```
